apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: helloworld
  description: |
    Dockererized Kubernetes Express Server App.
  links:
    - title: Git
      url: https://code-test.ssnc.dev/backstage-demo/fee
    - title: Documentation
      url: https://code-test.ssnc.dev/backstage-demo/fee
    - title: Designs 
      url: https://code-test.ssnc.dev/backstage-demo/fee
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/techdocs-ref: dir:.
    lighthouse.com/website-url: https://backstage.io
    gocd.org/pipelines: backstage,backstage-pr,backstage-builder
    backstage.io/kubernetes-namespace: backstage
    backstage.io/kubernetes-id: helloworld
    #backstage.io/kubernetes-label-selector: 'app=helloworld'
spec:
  type: service
  owner:  alpha
  lifecycle: experimental
  providesApis:
    - docker-hello-world

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  namespace: backstage
  name: helloworld
  description: Fee Engine API.
spec:
  type: asyncapi
  lifecycle: experimental
  owner: alpha
  definition: |
    asyncapi: 3.0.0
    info:
      title: Fee Engine API
      version: 1.0.0
      description: "The Fee Engine API"
    defaultContentType: application/json

---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: docker-desktop
  annotations:
    kubernetes.io/api-server: 'https://127.0.0.1:6443'
    kubernetes.io/api-server-certificate-authority: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJQ0xkN0xjOGc3aEl3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBek1UQXhNakkxTlRaYUZ3MHpOVEF6TURneE1qSTFOVFphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNmTFFvcHlGNnNyeUYzakZvOG8vb1ZaZ0lGNjVTVitHMEo0cUZwWi9WUmlqWDFaYklCM1cvVUJBZlAKQnlsRkt3TStLZFE2ZDdxQzFCcEwycm1Odk1nSU5MUTZlTm1YM2RnZ1EzeE5VS0ZkNFJyQTk0RWFPem9KNnJyUApGUnZwdzZCYkRwVWdCTjJxNXJsQzdZVHNpT0R0ekZZMk96YVNtOEV0cENFbEhoYmZKcys3K0xJcjJmc2MzaXZMCk5WYjVpdU9zTlhoNFlJcHcvVWJGWDR3bEZhYkdlM2dXQkoyTjhnM3loSlZEVjNaK0R6REc3TVp2UGNNNjl3UEsKdlUzWk5FZDJNMmJlaTNWbWQxbmgrWklxYnlhV2dmTmNUbEwwdndNcmpHNGxXQlJTZEo2TnhxRTZWa1BxWDZLMgpGYldla3ppTHRJb2Q0V3BhOHIvdnkvZmtLZUVUQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTeUZ5U2ZCTUgxQVVlZC8zN05ObzNpWTVXVVhEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQkpiVnBXOWVCdApWaWJhTlVhQ0ZHNUtEL2hTbXJWMkxweTlscGIrVVJXZ3YvN1FNV2J4ajNZSFZqN2Q1anVlaUFSS2RUVExIeldoCjdWeTI0NEJYWUJrL2ZXODh0VzRVNkxyTFRLTFI2ajM4UDVUaW9ZeXZWYXBwZXdMdXFvUEh4YmdaU2VYYkorVWYKZ2ozajR1UGphTVE3aGExTVVPWUU3ZmRGekUxUDhZUjBGZndzVUx2M3FwZE05KzR4Q1NORzhtRG5FR1dUNE9zRQo4V01mb3IrS0M0c0tERkwvRWtCYmp0amgzNHZ5SmNKVElRVkxRZFdwOFRSYUJqeGpacWtHMzZMV2lPa1hpdHBoClpWYUh4Tk52WHJmeHJ0QXgvdUVWdmVoSkV1SklVR212OUROaVRWczdXSWRkRlNuTEJZNWliQUJISDRoZlMzYTMKYkdWcElQaHJrS0pKCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K # base64-encoded CA
    kubernetes.io/auth-provider: 'serviceAccount'
    #kubernetes.io/oidc-token-provider: 'microsoft'
    kubernetes.io/skip-metrics-lookup: 'true'
    kubernetes.io/skip-tls-verify: 'false'
    kubernetes.io/service-account-token: 'eyJhbGciOiJSUzI1NiIsImtpZCI6IkRmNFp3MmZlNDBVNDMzWFYxUWR2YmM4ekl1ZUNVOEVpbThtSEFCTTJ1SzgifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlcm5ldGVzLWRhc2hib2FyZCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJhZG1pbi11c2VyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImFkbWluLXVzZXIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiIwZWEyYzhiNy1mYjQ5LTQ4YTgtOGNiMS00ZjFmYzU3Mjk0NzQiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZXJuZXRlcy1kYXNoYm9hcmQ6YWRtaW4tdXNlciJ9.W0cYd7LKWLf6-st4z3gh0li9BOnS7n0pJH_XnrQ_pz3w_PkUgK8H--AuDFu3P1F4_KiaaTEzG3iabXC5XZMqGWUeOq0L0lagscigWq3xfeK9eMo6fIaRtqQilvHgYbY5pnb6NLo2iOLDIeWLJUSFcKZZffGZmEo82JpiSiOA_y35KWE7yBhroZUCmR3ncQIsL1xa_OULYIV2x1YusKpeQksxyvqt2vWQF-WM2AtC1Jr8br4J_ID8pZw4WNnhL9kDZGxkoFmavQMk6osYI_gYSea1TcTYZwckrd6YGH9lnXaXpAieo83mgAY8Ldfs9kyzBOCZ9Uti0uLl5JE58lh-fw'
    #kubernetes.io/dashboard-url: 'http://localhost:8001'
    backstage.io/kubernetes-dashboard-app: 'standard'
    backstage.io/kubernetes-dashboard-title: 'my-local-docker-desktop'
    backstage.io/kubernetes-dashboard-ca-data: 'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJQ0xkN0xjOGc3aEl3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBek1UQXhNakkxTlRaYUZ3MHpOVEF6TURneE1qSTFOVFphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNmTFFvcHlGNnNyeUYzakZvOG8vb1ZaZ0lGNjVTVitHMEo0cUZwWi9WUmlqWDFaYklCM1cvVUJBZlAKQnlsRkt3TStLZFE2ZDdxQzFCcEwycm1Odk1nSU5MUTZlTm1YM2RnZ1EzeE5VS0ZkNFJyQTk0RWFPem9KNnJyUApGUnZwdzZCYkRwVWdCTjJxNXJsQzdZVHNpT0R0ekZZMk96YVNtOEV0cENFbEhoYmZKcys3K0xJcjJmc2MzaXZMCk5WYjVpdU9zTlhoNFlJcHcvVWJGWDR3bEZhYkdlM2dXQkoyTjhnM3loSlZEVjNaK0R6REc3TVp2UGNNNjl3UEsKdlUzWk5FZDJNM'
#spec:
  #type: kubernetes-cluster
  #owner: user:guest

---

# catalog-info.yaml
# apiVersion: backstage.io/v1alpha1
# kind: Resource
# metadata:
#   name: docker-desktop
#   annotations:
#     backstage.io/kubernetes-auth-provider: serviceAccount
# spec:
#   type: kubernetes-cluster
#   owner: lyric-service
#   parameters:
#     url: https://127.0.0.1:6443
#     name: docker-desktop
#     authProvider: serviceAccount
#     serviceAccountToken: 'eyJhbGciOiJSUzI1NiIsImtpZCI6IkRmNFp3MmZlNDBVNDMzWFYxUWR2YmM4ekl1ZUNVOEVpbThtSEFCTTJ1SzgifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlcm5ldGVzLWRhc2hib2FyZCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJhZG1pbi11c2VyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImFkbWluLXVzZXIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiIwZWEyYzhiNy1mYjQ5LTQ4YTgtOGNiMS00ZjFmYzU3Mjk0NzQiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZXJuZXRlcy1kYXNoYm9hcmQ6YWRtaW4tdXNlciJ9.W0cYd7LKWLf6-st4z3gh0li9BOnS7n0pJH_XnrQ_pz3w_PkUgK8H--AuDFu3P1F4_KiaaTEzG3iabXC5XZMqGWUeOq0L0lagscigWq3xfeK9eMo6fIaRtqQilvHgYbY5pnb6NLo2iOLDIeWLJUSFcKZZffGZmEo82JpiSiOA_y35KWE7yBhroZUCmR3ncQIsL1xa_OULYIV2x1YusKpeQksxyvqt2vWQF-WM2AtC1Jr8br4J_ID8pZw4WNnhL9kDZGxkoFmavQMk6osYI_gYSea1TcTYZwckrd6YGH9lnXaXpAieo83mgAY8Ldfs9kyzBOCZ9Uti0uLl5JE58lh-fw'
#     caData: 'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJQ0xkN0xjOGc3aEl3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBek1UQXhNakkxTlRaYUZ3MHpOVEF6TURneE1qSTFOVFphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNmTFFvcHlGNnNyeUYzakZvOG8vb1ZaZ0lGNjVTVitHMEo0cUZwWi9WUmlqWDFaYklCM1cvVUJBZlAKQnlsRkt3TStLZFE2ZDdxQzFCcEwycm1Odk1nSU5MUTZlTm1YM2RnZ1EzeE5VS0ZkNFJyQTk0RWFPem9KNnJyUApGUnZwdzZCYkRwVWdCTjJxNXJsQzdZVHNpT0R0ekZZMk96YVNtOEV0cENFbEhoYmZKcys3K0xJcjJmc2MzaXZMCk5WYjVpdU9zTlhoNFlJcHcvVWJGWDR3bEZhYkdlM2dXQkoyTjhnM3loSlZEVjNaK0R6REc3TVp2UGNNNjl3UEsKdlUzWk5FZDJNM
#     skipTLSVerify: false
#     skipMetricsLookup: true
