apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    name: a-hello-from-docker
    description: A Express Server hello-from-docker
    annotations:
        'backstage.io/kubernetes-namespace': backstage
    links:
        - url: https://admin.example-org.com
          title: Admin Dashboard
          icon: dashboard
          type: admin-dashboard
spec:
    type: service
    lifecycle: production
    owner: idpadmins
    system: project-x

---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
    name: project-x
    description: Handy tools to keep artists in the loop
spec:
    owner: artist-relations-team
    domain: artists
